test:nightly:
  image: riot/riotbuild
  script:
  - "if [ -e RIOT ]; then (cd RIOT; git pull); else git clone https://github.com/RIOT-OS/RIOT; fi"
  - "(cd RIOT && git reset --hard)"
  - "for FILE in RIOT/{examples/rust-{hello-world,gcoap},tests/rust_minimal}/Cargo.toml; do echo '[patch.crates-io]' >> $FILE; echo 'riot-sys = { path = \"../../../\" }' >> $FILE; done"
  - "for BOARD in `make --quiet -C RIOT/examples/rust-hello-world info-boards-supported`; do make -C RIOT/examples/rust-hello-world BOARD=${BOARD} all || exit 1; done"
  - "for BOARD in `make --quiet -C RIOT/examples/rust-gcoap info-boards-supported`; do make -C RIOT/examples/rust-gcoap BOARD=${BOARD} all || exit 1; done"
  - "for BOARD in `make --quiet -C RIOT/tests/rust_minimal info-boards-supported`; do make -C RIOT/tests/rust_minimal BOARD=${BOARD} all || exit 1; done"
  cache:
    paths:
      - .cargo/
      - RIOT
