[package]
name = "riot-sys"
version = "0.1.0"
authors = ["chrysn <chrysn@fsfe.org>"]

[dependencies]
embedded-hal = "0.2.0"

[build-dependencies]
# bindgen = "0.40.0"
# .40 is not released yet; until then:
bindgen = { path = "../../../../../../git/crates/bindgen" }
