[package]
name = "riot-sys"
version = "0.2.1"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]

description = "Rust FFI wrappers for the RIOT operating system"
documentation = "https://docs.rs/riot-sys/"
repository = "https://gitlab.com/etonomy/riot-sys"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings"]
categories = ["external-ffi-bindings", "no-std"]
license = "LGPL-2.1"

[build-dependencies]
bindgen = "0.43.2"
shlex = "0.1.1"
