[package]
name = "riot-sys"
version = "0.4.2"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]
edition = "2018"

description = "Rust FFI wrappers for the RIOT operating system"
documentation = "https://rustdoc.etonomy.org/riot_sys/"
repository = "https://gitlab.com/etonomy/riot-sys"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings"]
categories = ["external-ffi-bindings", "no-std"]
license = "LGPL-2.1"

links = "riot-sys"

[dependencies]
cty = "^0.2"
c2rust-asm-casts = "0.2"
# Relevant for some boards like the wemos-zero
c2rust-bitfields = { version = "0.3", features = ["no_std"] }
# nightly is required to get the const properties that the previous own implementation had
cstr_core = { version = "^0.2.4", default-features = false, features = [ "nightly" ] }

[build-dependencies]
bindgen = "0.53.1"
shlex = "^1"
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }
