[package]
name = "riot-sys"
version = "0.3.0"
authors = ["Christian M. Amsüss <ca@etonomy.org>"]
edition = "2018"

description = "Rust FFI wrappers for the RIOT operating system"
documentation = "https://rustdoc.etonomy.org/riot_sys/"
repository = "https://gitlab.com/etonomy/riot-sys"
readme = "README.md"
keywords = ["riot", "riot-os", "iot", "bindings"]
categories = ["external-ffi-bindings", "no-std"]
license = "LGPL-2.1"

[dependencies]
cty = "^0.2"
# see https://github.com/immunant/c2rust/pull/307 -- it's merged, but not published yet
c2rust-asm-casts = { git = "https://github.com/immunant/c2rust" }
# Relevant for some boards like the wemos-zero
c2rust-bitfields = { version = "0.3", features = ["no_std"] }

[build-dependencies]
bindgen = "0.53.1"
shlex = "0.1.1"
serde_json = "1"
