name: Formal checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    container: docker.io/rust
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add rustfmt component
      run: rustup component add rustfmt
    - name: Run cargo-fmt
      run: cargo fmt --check

  cargo-readme:
    runs-on: ubuntu-latest
    container: docker.io/rust
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-readme
        version: latest
    - name: Verify that README.rst is up to date
      run: cargo readme | diff /dev/stdin README.md
